### PR TITLE
oauth2 api endpoint & better template

### PR DESCRIPTION
**Pull request by drwelby**
This should finish out the provider side so users can use their MapStory account to log into AskBot and the wiki.

### CODE REVIEW

**Comment by ischneider** [comment]
@drwelby I deployed this to dev. On wiki, I get an error:

> Sorry, an error occurred:
> The requested redirect didn't match the client settings. 

Does something need to be deployed to askbot or am I missing something?

**Comment by drwelby** [comment]
Yes, changes will need to be made to both Askbot and the wiki. Now that
it's deployed on the MapStory side I can set up the wiki myself. For
AskBot, how do you want to update that one - I'm not sure where it is.
The other question is do we want this to work only for dev accounts for
now, or do we need to jump to production as soon as possible?

**Comment by jonpmarino** [comment]
@drwelby thanks for working on this. For what its worth, I'm interested in getting this going on on production as soon as reasonably possible. Its an important pre-req for getting folks involved in the community

**Comment by ischneider** [comment]
@drwelby i deployed stuff to production. Ping me tomorrow for dealing w/ askbot?

**Pull request merged**
