### PR TITLE
Initial work on adding twitter card meta tags to the layer and map pages

### PR DESCRIPTION
**Pull request by jj0hns0n**
refs #500

This adds the initial summary card meta tags to the layer and map page. They were tested on dev, but the twitter card preview tool seems to be broken (not even displaying nytimes links that should work). I will circle back and test this. 

Next steps after making sure this works with the preview tool are to ask for the site to be whitelisted and then make some experiments with the player in an iframe. Not sure if we need to do the player, a summary and link may be fine.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
Twitter's preview tool is working now, and this works. You can try it out yourself with layers/maps on dev.
Preview your Twitter Card Twitter Developers

**Comment by jj0hns0n** [comment]
@jonpmarino @cholmes check above.

**Comment by jonpmarino** [comment]
awesome! Just tried, though and got a tweet that looked like the image below. Just tweeted from Share This buttons on dev. What am I missing?
tweet

**Comment by jj0hns0n** [comment]
Doesnt work on twitter itself yet. We have to demonstrate it works in the
preview thing (check) and then ask twitter to whitelist us. Nice thing is
that apparently an old acquaintance of mine does the approvals, so once
this is pulled onto production, it shouldnt take long.

If you want to test yourself, check here
https://dev.twitter.com/docs/cards/preview ... let me know if you run into
any issues with that. NOTE: It was just totally broken last night, so if
you get an error about technical problems, its probably on twitters end.

Fwiw, Once this is in place, we can try to upgrade it to the photo or
embedded video one. I wanted to get this through first. In order to the
video one, you have to demonstrate that it works in several different
clients which is no small order.

Lemme know if you have any questions.

**Comment by jonpmarino** [comment]
Got it. And strategy makes sense. Exciting about connection.

**Comment by ischneider** [comment]
merged with 0bdeee9326a6c3bd240f83087e56e2e02a2a46cf

**Pull request closed without merging**
