### PR TITLE
Add social login to all login/register pages

### PR DESCRIPTION
**Pull request by jj0hns0n**
Branches from issue-624 ... @ischneider still a few questions about registration. Looks like /account/signup/ and /accounts/register/ both exist but the latter may never be used. Lets discuss ASAP.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
MapStory _ MapStory-2
MapStory _ Login
MapStory _ Login-1

**Comment by ischneider** [comment]
@jj0hns0n , the latter (/accounts/register) is closed on dev/production and you're correct, we're not using it directly.
Ideally, we should just override that URL with a redirect

**Comment by ischneider** [comment]
@jj0hns0n went ahead and redirected the old URL with c30605924d84b12dc46521f08631d6818d58c003

**Comment by jonpmarino** [comment]
Question we got asked us about social login...if someone uses their FB or Twitter to log-in, does MapStory retain any of their details for its own databases? And, if they stop using one of the accounts they use to sign-in with, does that mean their MapStory profile and content goes away as well?

**Comment by ischneider** [comment]
To the best of my knowledge, we will get some kind of user id, email and if possible, a URL to an image.

I honestly don't know what happens if they stop using a social account. To the best of my knowledge, the account would not be accessible until they reset their password though nothing should go away.

**Pull request merged**
